// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, status, players, rounds, settings, last_activity, host_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, status, players, rounds, settings, created_at, updated_at, last_activity, host_id
`

type CreateGameParams struct {
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CreateGameRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Code,
		arg.Status,
		arg.Players,
		arg.Rounds,
		arg.Settings,
		arg.LastActivity,
		arg.HostID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateGameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Players,
		&i.Rounds,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
		&i.HostID,
	)
	return i, err
}

const deleteGameByCode = `-- name: DeleteGameByCode :exec
DELETE FROM games
WHERE code = $1
`

func (q *Queries) DeleteGameByCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteGameByCode, code)
	return err
}

const getGameByCode = `-- name: GetGameByCode :one
SELECT id, code, status, players, rounds, settings, created_at, updated_at, last_activity, host_id
FROM games
WHERE code = $1
LIMIT 1
`

type GetGameByCodeRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
}

func (q *Queries) GetGameByCode(ctx context.Context, code string) (GetGameByCodeRow, error) {
	row := q.db.QueryRow(ctx, getGameByCode, code)
	var i GetGameByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Players,
		&i.Rounds,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
		&i.HostID,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, code, status, players, rounds, settings, created_at, updated_at, last_activity, host_id
FROM games
WHERE id = $1
LIMIT 1
`

type GetGameByIDRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
}

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (GetGameByIDRow, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i GetGameByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Players,
		&i.Rounds,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
		&i.HostID,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET status = $1,
    players = $2,
    rounds = $3,
    settings = $4,
    last_activity = $5,
    host_id = $6,
    updated_at = $7
WHERE code = $8
RETURNING id, code, status, players, rounds, settings, created_at, updated_at, last_activity, host_id
`

type UpdateGameParams struct {
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Code         string             `db:"code" json:"code"`
}

type UpdateGameRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Status       string             `db:"status" json:"status"`
	Players      []byte             `db:"players" json:"players"`
	Rounds       []byte             `db:"rounds" json:"rounds"`
	Settings     []byte             `db:"settings" json:"settings"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (UpdateGameRow, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.Status,
		arg.Players,
		arg.Rounds,
		arg.Settings,
		arg.LastActivity,
		arg.HostID,
		arg.UpdatedAt,
		arg.Code,
	)
	var i UpdateGameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.Players,
		&i.Rounds,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivity,
		&i.HostID,
	)
	return i, err
}
