// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_invites.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameInvite = `-- name: CreateGameInvite :one
INSERT INTO game_invites (id, game_id, from_user, to_user, status, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, game_id, from_user, to_user, status, created_at, expires_at
`

type CreateGameInviteParams struct {
	ID        string             `db:"id" json:"id"`
	GameID    string             `db:"game_id" json:"game_id"`
	FromUser  string             `db:"from_user" json:"from_user"`
	ToUser    string             `db:"to_user" json:"to_user"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateGameInvite(ctx context.Context, arg CreateGameInviteParams) (GameInvite, error) {
	row := q.db.QueryRow(ctx, createGameInvite,
		arg.ID,
		arg.GameID,
		arg.FromUser,
		arg.ToUser,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i GameInvite
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.FromUser,
		&i.ToUser,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteGameInvite = `-- name: DeleteGameInvite :exec
DELETE FROM game_invites
WHERE id = $1
`

func (q *Queries) DeleteGameInvite(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGameInvite, id)
	return err
}

const getGameInviteByID = `-- name: GetGameInviteByID :one
SELECT id, game_id, from_user, to_user, status, created_at, expires_at
FROM game_invites
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGameInviteByID(ctx context.Context, id string) (GameInvite, error) {
	row := q.db.QueryRow(ctx, getGameInviteByID, id)
	var i GameInvite
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.FromUser,
		&i.ToUser,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingGameInvites = `-- name: GetPendingGameInvites :many
SELECT id, game_id, from_user, to_user, status, created_at, expires_at
FROM game_invites
WHERE to_user = $1
  AND status = 'pending'
  AND expires_at > $2
ORDER BY created_at DESC
`

type GetPendingGameInvitesParams struct {
	ToUser    string             `db:"to_user" json:"to_user"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetPendingGameInvites(ctx context.Context, arg GetPendingGameInvitesParams) ([]GameInvite, error) {
	rows, err := q.db.Query(ctx, getPendingGameInvites, arg.ToUser, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameInvite{}
	for rows.Next() {
		var i GameInvite
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.FromUser,
			&i.ToUser,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameInviteStatus = `-- name: UpdateGameInviteStatus :one
UPDATE game_invites
SET status = $1
WHERE id = $2
RETURNING id, game_id, from_user, to_user, status, created_at, expires_at
`

type UpdateGameInviteStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) UpdateGameInviteStatus(ctx context.Context, arg UpdateGameInviteStatusParams) (GameInvite, error) {
	row := q.db.QueryRow(ctx, updateGameInviteStatus, arg.Status, arg.ID)
	var i GameInvite
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.FromUser,
		&i.ToUser,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
