// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores game sessions and their state
type Game struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Code   string      `db:"code" json:"code"`
	Status string      `db:"status" json:"status"`
	// JSON array of player objects
	Players []byte `db:"players" json:"players"`
	// JSON array of round objects
	Rounds       []byte             `db:"rounds" json:"rounds"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Settings     []byte             `db:"settings" json:"settings"`
	LastActivity pgtype.Timestamptz `db:"last_activity" json:"last_activity"`
	HostID       string             `db:"host_id" json:"host_id"`
}

type GameInvite struct {
	ID        string             `db:"id" json:"id"`
	GameID    string             `db:"game_id" json:"game_id"`
	FromUser  string             `db:"from_user" json:"from_user"`
	ToUser    string             `db:"to_user" json:"to_user"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// Stores trivia questions with optional images
type Question struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Text          string      `db:"text" json:"text"`
	Answer        string      `db:"answer" json:"answer"`
	Category      string      `db:"category" json:"category"`
	FillerAnswers []string    `db:"filler_answers" json:"filler_answers"`
	// Path to the question image file
	ImagePath pgtype.Text `db:"image_path" json:"image_path"`
	// Alt text for the question image
	ImageAlt  pgtype.Text        `db:"image_alt" json:"image_alt"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           string             `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	GamesPlayed  int32              `db:"games_played" json:"games_played"`
	GamesWon     int32              `db:"games_won" json:"games_won"`
	TotalPoints  int32              `db:"total_points" json:"total_points"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
