// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (text, answer, category, filler_answers)
VALUES ($1, $2, $3, $4)
RETURNING id, text, answer, category, filler_answers, created_at, updated_at
`

type CreateQuestionParams struct {
	Text          string   `db:"text" json:"text"`
	Answer        string   `db:"answer" json:"answer"`
	Category      string   `db:"category" json:"category"`
	FillerAnswers []string `db:"filler_answers" json:"filler_answers"`
}

type CreateQuestionRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Text          string             `db:"text" json:"text"`
	Answer        string             `db:"answer" json:"answer"`
	Category      string             `db:"category" json:"category"`
	FillerAnswers []string           `db:"filler_answers" json:"filler_answers"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (CreateQuestionRow, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.Text,
		arg.Answer,
		arg.Category,
		arg.FillerAnswers,
	)
	var i CreateQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Answer,
		&i.Category,
		&i.FillerAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :execrows
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuestion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, text, answer, category, filler_answers, created_at, updated_at
FROM questions
WHERE id = $1
LIMIT 1
`

type GetQuestionByIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Text          string             `db:"text" json:"text"`
	Answer        string             `db:"answer" json:"answer"`
	Category      string             `db:"category" json:"category"`
	FillerAnswers []string           `db:"filler_answers" json:"filler_answers"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (GetQuestionByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i GetQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Answer,
		&i.Category,
		&i.FillerAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionCategories = `-- name: GetQuestionCategories :many
SELECT DISTINCT category
FROM questions
ORDER BY category
`

func (q *Queries) GetQuestionCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getQuestionCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomQuestion = `-- name: GetRandomQuestion :one
SELECT id, text, answer, category, filler_answers, created_at, updated_at
FROM questions
WHERE category = $1
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomQuestionRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Text          string             `db:"text" json:"text"`
	Answer        string             `db:"answer" json:"answer"`
	Category      string             `db:"category" json:"category"`
	FillerAnswers []string           `db:"filler_answers" json:"filler_answers"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetRandomQuestion(ctx context.Context, category string) (GetRandomQuestionRow, error) {
	row := q.db.QueryRow(ctx, getRandomQuestion, category)
	var i GetRandomQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Answer,
		&i.Category,
		&i.FillerAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET text = $1,
    answer = $2,
    category = $3,
    filler_answers = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, text, answer, category, filler_answers, created_at, updated_at
`

type UpdateQuestionParams struct {
	Text          string      `db:"text" json:"text"`
	Answer        string      `db:"answer" json:"answer"`
	Category      string      `db:"category" json:"category"`
	FillerAnswers []string    `db:"filler_answers" json:"filler_answers"`
	ID            pgtype.UUID `db:"id" json:"id"`
}

type UpdateQuestionRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Text          string             `db:"text" json:"text"`
	Answer        string             `db:"answer" json:"answer"`
	Category      string             `db:"category" json:"category"`
	FillerAnswers []string           `db:"filler_answers" json:"filler_answers"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (UpdateQuestionRow, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.Text,
		arg.Answer,
		arg.Category,
		arg.FillerAnswers,
		arg.ID,
	)
	var i UpdateQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Answer,
		&i.Category,
		&i.FillerAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
