// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           string             `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	GamesPlayed  int32              `db:"games_played" json:"games_played"`
	GamesWon     int32              `db:"games_won" json:"games_won"`
	TotalPoints  int32              `db:"total_points" json:"total_points"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.GamesPlayed,
		arg.GamesWon,
		arg.TotalPoints,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $1,
    email = $2,
    password_hash = $3,
    display_name = $4,
    games_played = $5,
    games_won = $6,
    total_points = $7,
    last_login_at = $8,
    updated_at = $9
WHERE id = $10
RETURNING id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	GamesPlayed  int32              `db:"games_played" json:"games_played"`
	GamesWon     int32              `db:"games_won" json:"games_won"`
	TotalPoints  int32              `db:"total_points" json:"total_points"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID           string             `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.GamesPlayed,
		arg.GamesWon,
		arg.TotalPoints,
		arg.LastLoginAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStats = `-- name: UpdateUserStats :one
UPDATE users
SET games_played = $1,
    games_won = $2,
    total_points = $3,
    updated_at = $4
WHERE id = $5
RETURNING id, username, email, password_hash, display_name, games_played, games_won, total_points, last_login_at, created_at, updated_at
`

type UpdateUserStatsParams struct {
	GamesPlayed int32              `db:"games_played" json:"games_played"`
	GamesWon    int32              `db:"games_won" json:"games_won"`
	TotalPoints int32              `db:"total_points" json:"total_points"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID          string             `db:"id" json:"id"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStats,
		arg.GamesPlayed,
		arg.GamesWon,
		arg.TotalPoints,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalPoints,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
